### ISSUE TITLE
Inspecting item entities

### ISSUE THREAD

**Issue by redstonekasi** [wisp-forest/gadget#10]
Not sure how you handle detecting which entity you're looking at, but I can't seem to inspect item entities.

**Comment by BasiqueEvangelist** [comment]
Right now it uses the game's `crosshairTarget`, which AFAIK doesn't target items. I might make it use a custom raycast method instead

**Comment by BasiqueEvangelist** [comment]
Fixed in 1abe08f112086f575e31b491526ccae541031e2e, will close after I release

**Comment by redstonekasi** [comment]
I'm not familiar with the functions used there, but that seems like it'd no longer allow you to inspect yourself?

**Comment by BasiqueEvangelist** [comment]
The relevant code for inspecting yourself is https://github.com/wisp-forest/gadget/blob/master/src/main/java/io/wispforest/gadget/client/GadgetClient.java#L116-L121, which still works

**Comment by redstonekasi** [comment]
Ah okay, I didn't see that, sorry!
