### ISSUE TITLE
Search fields

### ISSUE THREAD

**Issue by redstonekasi** [wisp-forest/gadget#11]
Add the ability to search for fields in the inspector, it can be quite difficult to locate what you want to inspect in large objects.

**Comment by BasiqueEvangelist** [comment]
Implemented in d2f795041aa70af92a33f399ac4ae1cc872ce0c8, will close after I release

**Comment by BasiqueEvangelist** [comment]
Fixed in 0.1.5

**Comment by redstonekasi** [comment]
Is it possible to make it possible to put focus on the search bar by pressing CTRL+F or something like that?

**Comment by redstonekasi** [comment]
On a separate note, searching just crashed my client, seems to happen when zero results were found.

https://github.com/wisp-forest/gadget/blob/3d9cc0b47966b1cdb24edbb38cc45ba58610d7bf/src/main/java/io/wispforest/gadget/client/gui/search/SearchGui.java#L76

**Comment by BasiqueEvangelist** [comment]
I'm getting the feeling that I'll have to find QA testers
