### ISSUE TITLE
Submitting edited NBT value collapses the tree

### ISSUE THREAD

**Issue by redstonekasi** [wisp-forest/gadget#12]

**Comment by BasiqueEvangelist** [comment]
I thought this wasn't an issue :raised_eyebrow:
Can you send an example?

**Comment by BasiqueEvangelist** [comment]
Oh, you mean the NBT field object tree...

**Comment by BasiqueEvangelist** [comment]
Fixed in 92ede95052e2b142ca375ed3b92fb99a1518f8f8, will close after I release
