### ISSUE TITLE
[Feature Request] Dump Packets as Plaintext

### ISSUE THREAD

**Issue by Kas-tle** [wisp-forest/gadget#15]
I just want to say amazing work on the in-game inspector for packets. It's amazingly functional for being built within the constraints of Minecraft's GUI. That said, I would still really appreciate the ability to have these dumps in plaintext to examine outside of Minecraft.

**Comment by BasiqueEvangelist** [comment]
Actually, question: how would this work?
The in-game packet inspector works just deserializes the packets and uses gadget's existing field inspecting infrastructure to show everything in it. Should I just recursively dump fields until a certain depth?

**Comment by Kas-tle** [comment]
Yeah that sounds like it would work if a depth limit would be needed for performance reasons. Basically it would be nice to sort of have everything I could see in the packet inspector, were I to expand all fields, in plain text so that it would be easily searchable

**Comment by BasiqueEvangelist** [comment]
Depends on #19

**Comment by BasiqueEvangelist** [comment]
I finally got the plain text dump exporting working...
[2023-04-18_22.22.07.gdump.txt](https://github.com/wisp-forest/gadget/files/11362581/2023-04-18_22.22.07.gdump.txt)

I probably need to fix up some usability issues with byte arrays and stuff, but it works!

**Comment by BasiqueEvangelist** [comment]
Kinda forgot about this issue, but it should be fixed in [0.2.0+1.19.4](https://modrinth.com/mod/gadget/version/0.2.0+1.19.4)

**Comment by Kas-tle** [comment]
Thank you!
