### ISSUE TITLE
[Bug] Scrolling in Server Menu Does Not Work with Gadget Installed

### ISSUE THREAD

**Issue by Kas-tle** [wisp-forest/gadget#16]
With the latest version of gadget installed, scrolling does not work in the server menu. To reproduce:

1. Download the latest fabric installer ([0.11.2](https://fabricmc.net/use/installer/)) and install 1.19.3 with loader version 0.14.17. Run the installer.
2. Install [gadget-0.1.7+1.19.3.jar](https://github.com/wisp-forest/gadget/releases/download/0.1.7%2B1.19.3/gadget-0.1.7+1.19.3.jar), [Fabric API 0.76.0+1.19.3](https://www.curseforge.com/minecraft/mc-mods/fabric-api/files/4438742), and [owo-lib-0.10.3+1.19.3.jar](https://github.com/wisp-forest/owo-lib/releases/download/0.10.3%2B1.19.3/owo-lib-0.10.3+1.19.3.jar).
3. Launch the installed 1.19.3 fabric profile.
4. Select the "Multiplayer" menu.
5. Attempt to use the scroll wheel to scroll through the server list.
6. Observe that the scroll wheel does not work and the scroll bar must be manually dragged instead.
7. Stop the game.
8. Uninstall [gadget-0.1.7+1.19.3.jar](https://github.com/wisp-forest/gadget/releases/download/0.1.7%2B1.19.3/gadget-0.1.7+1.19.3.jar).
9. Launch the 1.19.3 fabric profile again, navigate to the "Multiplayer" menu, and again attempt to scroll via the scroll wheel.
10. Observe that normal scrolling behavior is restored.

Expected outcome: the scroll wheel works in the "Multiplayer" menu
Actual outcome: the scroll wheel does not work in the "Multiplayer" menu

System Info:
- Logs: [latest.log](https://gist.github.com/Kas-tle/7e324febdd22e32490334ba38867a222)
- OS: Windows 11 Pro 22H2

**Comment by BasiqueEvangelist** [comment]
I think I've already fixed this in main, but haven't released it
~~I probably should~~

**Comment by Kas-tle** [comment]
Ah indeed it is. My bad.
