### ISSUE TITLE
[Feature Request] Cleanly attempt to save the dump on crash.

### ISSUE THREAD

**Issue by Ampflower** [wisp-forest/gadget#21]
In case there's packets that causes a crash, try to save so it's possible to inspect later.

May also include using a timer to flush ever so often so that if there's a JVM crash or a SIGKILL, it can still save something, although potential caveat that it may miss something unless there's an on every packet mode as well.

**Comment by BasiqueEvangelist** [comment]
I've added flushing after every written packet in 3d01bcabbac5ca569cae979a86266dc8c0514ee4, so this should be fixed™
Haven't tested much, though

**Comment by BasiqueEvangelist** [comment]
Done in [0.2.1+1.20](https://modrinth.com/mod/gadget/version/0.2.1+1.20)
