### ISSUE TITLE
Game mode change with F3 + F4 broken

### ISSUE THREAD

**Issue by 2mal3** [wisp-forest/gadget#7]
If you try to change the game mode with F3 and F4, the corresponding menu is opened and the next game mode is selected, but you cannot change to any other game mode. For example, in the video I can only switch between creative to survival, but not to spectator or adventure.

https://user-images.githubusercontent.com/56305732/201471456-5c75790d-73e0-4cc8-ba0a-bbb9383e8c60.mp4

Minecraft 1.19.2, gadget 0.1.1, Fabric API 0.64.0, Fabric Loader 0.14.10

**Comment by BasiqueEvangelist** [comment]
Why didn't I test that :worried:
You should be able to mitigate it by disabling `Debug Keys In Screens` in the config, I'll make a release fixing this when I finish the other stuff I was working on™

**Comment by 2mal3** [comment]
Yes, that works, thanks.

**Comment by BasiqueEvangelist** [comment]
Fixed in 082a72232c47eb8d8187e8f247df03695d026b32, will close after release

**Comment by BasiqueEvangelist** [comment]
Fixed in 0.1.2
